image: docker:latest

cache:
  paths:
  - .cache/

services:
- docker:dind

stages:
- build
- verification

build:
  stage: build
  script:
  - .ci/ci.sh ./gradlew clean build
  artifacts:
    reports:
      junit:
        - cucumber/build/reports/tests/gemini4j/
        - cucumber/build/reports/tests/test/

sonar:
  stage: verification
  script:
  - .ci/ci.sh ./gradlew sonarqube -Dsonar.projectKey=dajudge_gemini4j -Dsonar.organization=dajudge-github -Dsonar.host.url=https://sonarcloud.io -Dsonar.login=${SONAR_TOKEN}
