image: docker:latest

cache:
  paths:
  - .cache/

services:
- docker:dind

build-master:
  stage: build
  script:
  - .ci/ci.sh ./gradlew clean build
  artifacts:
    paths:
    - cucumber/build/reports/tests/gemini4j/
