apiVersion: v1
kind: Namespace
metadata:
  name: gemini4j
---
apiVersion: v1
kind: Secret
metadata:
  name: regcred
  namespace: gemini4j
  annotations:
    replicator.v1.mittwald.de/replicate-from: default/regcred
type: kubernetes.io/dockerconfigjson
data:
  .dockerconfigjson: eyJhdXRocyI6eyJodHRwczovL2V4YW1wbGUuY29tIjp7InVzZXJuYW1lIjoidXNlcm5hbWUiLCJwYXNzd29yZCI6InBhc3N3b3JkIiwiZW1haWwiOiJtYWlsQGV4YW1wbGUuY29tIiwiYXV0aCI6ImNHeGhZMlZvYjJSc1pYST0ifX19
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: gemini4j
  namespace: gemini4j
  labels:
    app: gemini4j
spec:
  selector:
    matchLabels:
      app: gemini4j
  replicas: 1
  template:
    metadata:
      labels:
        app: gemini4j
    spec:
      containers:
      - name: nginx
        image: docker.alexstockinger.com:443/gemini4j:latest
        ports:
        - containerPort: 80
      imagePullSecrets:
        - name: regcred
---
apiVersion: v1
kind: Service
metadata:
  name: gemini4j
  namespace: gemini4j
  labels:
    app: gemini4j
spec:
  ports:
  - port: 80
    targetPort: 80
  selector:
    app: gemini4j
---
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: gemini4j
  namespace: gemini4j
  annotations:
    certmanager.k8s.io/cluster-issuer: 'letsencrypt-staging'
spec:
  rules:
  - host: 'www.gemini4j.org'
    http:
      paths:
      - path: /
        backend:
          serviceName: gemini4j
          servicePort: 80
  tls:
    - hosts:
      - 'www.gemini4j.org'
      secretName: gemini4j-tls
