apiVersion: v1
kind: Namespace
metadata:
  name: gemini4j
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: gemini4j
  namespace: gemini4j
  labels:
    app: gemini4j
spec:
  selector:
    matchLabels:
      app: gemini4j
  replicas: 1
  template:
    metadata:
      labels:
        timestamp: "${System.currentTimeMillis()}"
        app: gemini4j
    spec:
      containers:
      - name: nginx
        image: ${env.DOCKER_REGISTRY}/gemini4j/website:latest
        ports:
        - containerPort: 80
      imagePullSecrets:
        - name: docker-registry
---
apiVersion: v1
kind: Service
metadata:
  name: gemini4j
  namespace: gemini4j
  labels:
    app: gemini4j
spec:
  ports:
  - port: 80
    targetPort: 80
  selector:
    app: gemini4j
---
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: gemini4j
  namespace: gemini4j
  annotations:
    cert-manager.io/cluster-issuer: letsencrypt-prod
spec:
  rules:
  - host: 'www.gemini4j.org'
    http:
      paths:
      - path: /
        backend:
          serviceName: gemini4j
          servicePort: 80
  tls:
    - hosts:
      - 'www.gemini4j.org'
      secretName: gemini4j-tls
